version: '3.8'

services:
  be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - webapp

  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - webapp

volumes:
  node_modules: {}

networks:
  webapp:
    driver: bridge
